# Exercise 3: Numpy

Perform the follwing tasks:


In [0]:
#3.1: import the numpy library
import numpy as np

In [9]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10, 10)
A

array([[0.58308208, 0.38458906, 0.38363759, 0.42793668, 0.81660522,
        0.37845611, 0.78292036, 0.33105122, 0.12011705, 0.6476161 ],
       [0.40299854, 0.91044316, 0.88815473, 0.38306072, 0.13276799,
        0.92922047, 0.56980283, 0.70390823, 0.01033156, 0.75294423],
       [0.92603028, 0.72800162, 0.17930404, 0.62559451, 0.04245658,
        0.9069707 , 0.26310962, 0.08513166, 0.31805554, 0.63417088],
       [0.46710842, 0.08658496, 0.45430248, 0.47114799, 0.90945114,
        0.0253041 , 0.38909396, 0.0360746 , 0.88895629, 0.34038834],
       [0.62573807, 0.20626447, 0.4935807 , 0.80401218, 0.40925382,
        0.55518804, 0.21521689, 0.08972836, 0.02881443, 0.56650105],
       [0.34027059, 0.30348049, 0.57114399, 0.14518241, 0.86339097,
        0.88523719, 0.19393583, 0.00936269, 0.46679165, 0.46978287],
       [0.22061064, 0.94380699, 0.26295413, 0.17775371, 0.72933877,
        0.48901363, 0.34504099, 0.16962252, 0.40584359, 0.70061121],
       [0.82171721, 0.93588334, 0.523815 

In [13]:
#3.3: return only the odd rows of 
A[::2]

array([[0.58308208, 0.38458906, 0.38363759, 0.42793668, 0.81660522,
        0.37845611, 0.78292036, 0.33105122, 0.12011705, 0.6476161 ],
       [0.92603028, 0.72800162, 0.17930404, 0.62559451, 0.04245658,
        0.9069707 , 0.26310962, 0.08513166, 0.31805554, 0.63417088],
       [0.62573807, 0.20626447, 0.4935807 , 0.80401218, 0.40925382,
        0.55518804, 0.21521689, 0.08972836, 0.02881443, 0.56650105],
       [0.22061064, 0.94380699, 0.26295413, 0.17775371, 0.72933877,
        0.48901363, 0.34504099, 0.16962252, 0.40584359, 0.70061121],
       [0.86213034, 0.41321526, 0.40079028, 0.75934413, 0.08512961,
        0.99445882, 0.94272744, 0.70159567, 0.98126107, 0.82201428]])

In [14]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[2.78466808, 2.71787089, 2.21743458, 2.07760213, 2.09045791,
        2.15167957, 2.27797961, 2.96888044, 3.20675701, 2.4084077 ],
       [2.71787089, 4.19514073, 2.97392277, 1.50788076, 2.36918614,
        2.38915806, 2.64877531, 3.6192471 , 3.96595554, 2.59741081],
       [2.21743458, 2.97392277, 3.21524138, 1.53740596, 2.27470211,
        2.06702145, 2.20283378, 3.096432  , 3.69280604, 2.34204097],
       [2.07760213, 1.50788076, 1.53740596, 2.54060307, 1.6048571 ,
        1.97136967, 1.80327915, 2.57944892, 2.62513677, 2.05814367],
       [2.09045791, 2.36918614, 2.27470211, 1.6048571 , 2.17599631,
        1.84113193, 1.67347249, 2.50613576, 2.77978528, 2.36190616],
       [2.15167957, 2.38915806, 2.06702145, 1.97136967, 1.84113193,
        2.56054589, 2.18716675, 2.60151733, 2.74535497, 2.10925245],
       [2.27797961, 2.64877531, 2.20283378, 1.80327915, 1.67347249,
        2.18716675, 2.6146415 , 3.00172227, 2.78738549, 1.97510652],
       [2.96888044, 3.6192471 , 3.096432 

In [18]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 0.94425431, -0.10613297,  1.39425213,  0.15056264, -1.48523854,
         0.21703338, -1.32773197,  0.26409178, -0.44112702,  0.46941794],
       [-0.06837232,  0.8589587 ,  1.07953931,  0.96316371, -0.45526215,
        -0.63945346,  0.17755745,  0.04985834, -0.96817235, -0.52924232],
       [-0.56423763,  1.28565545,  0.04472951,  1.08764793, -0.39202874,
        -0.02714788, -0.5921524 , -0.37623563, -0.43962351,  0.35514369],
       [-0.51554506,  0.16221279, -0.18036399,  0.64803245,  2.07851228,
        -0.78465226,  0.20296877,  0.11137609, -0.23772174, -0.9180964 ],
       [ 0.73422491, -0.37729867, -0.16753894, -0.06662339,  0.27291501,
         0.57391134, -0.13981886,  0.42028836, -0.45712617, -0.39917424],
       [-0.00368641, -0.07300136,  0.15522451, -0.54951303,  0.34274214,
         1.01948079, -0.36223067,  0.07585285,  0.09426357, -0.50980124],
       [ 0.93554293,  0.61608714,  0.4073869 ,  0.76080728, -0.5842717 ,
        -0.49540902, -0.30611172, -0.62536173

In [0]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [21]:
np.where(A > 0.5, A / 2, A)

array([[0.29154104, 0.38458906, 0.38363759, 0.42793668, 0.40830261,
        0.37845611, 0.39146018, 0.33105122, 0.12011705, 0.32380805],
       [0.40299854, 0.45522158, 0.44407736, 0.38306072, 0.13276799,
        0.46461024, 0.28490142, 0.35195411, 0.01033156, 0.37647211],
       [0.46301514, 0.36400081, 0.17930404, 0.31279725, 0.04245658,
        0.45348535, 0.26310962, 0.08513166, 0.31805554, 0.31708544],
       [0.46710842, 0.08658496, 0.45430248, 0.47114799, 0.45472557,
        0.0253041 , 0.38909396, 0.0360746 , 0.44447814, 0.34038834],
       [0.31286904, 0.20626447, 0.4935807 , 0.40200609, 0.40925382,
        0.27759402, 0.21521689, 0.08972836, 0.02881443, 0.28325053],
       [0.34027059, 0.30348049, 0.285572  , 0.14518241, 0.43169549,
        0.4426186 , 0.19393583, 0.00936269, 0.46679165, 0.46978287],
       [0.22061064, 0.4719035 , 0.26295413, 0.17775371, 0.36466938,
        0.48901363, 0.34504099, 0.16962252, 0.40584359, 0.35030561],
       [0.4108586 , 0.46794167, 0.2619075

In [23]:
#vergleich
A

array([[0.58308208, 0.38458906, 0.38363759, 0.42793668, 0.81660522,
        0.37845611, 0.78292036, 0.33105122, 0.12011705, 0.6476161 ],
       [0.40299854, 0.91044316, 0.88815473, 0.38306072, 0.13276799,
        0.92922047, 0.56980283, 0.70390823, 0.01033156, 0.75294423],
       [0.92603028, 0.72800162, 0.17930404, 0.62559451, 0.04245658,
        0.9069707 , 0.26310962, 0.08513166, 0.31805554, 0.63417088],
       [0.46710842, 0.08658496, 0.45430248, 0.47114799, 0.90945114,
        0.0253041 , 0.38909396, 0.0360746 , 0.88895629, 0.34038834],
       [0.62573807, 0.20626447, 0.4935807 , 0.80401218, 0.40925382,
        0.55518804, 0.21521689, 0.08972836, 0.02881443, 0.56650105],
       [0.34027059, 0.30348049, 0.57114399, 0.14518241, 0.86339097,
        0.88523719, 0.19393583, 0.00936269, 0.46679165, 0.46978287],
       [0.22061064, 0.94380699, 0.26295413, 0.17775371, 0.72933877,
        0.48901363, 0.34504099, 0.16962252, 0.40584359, 0.70061121],
       [0.82171721, 0.93588334, 0.523815 